apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reviewvideo-app
  namespace: argocd
spec:
  project: default
  source:
    # IMPORTANTE: Altere para a URL do seu repositório Git
    repoURL: https://github.com/paragao01/gitops-argocd.git
    path: k8s-webpage
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
