apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webpage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paragao01/devops4devs.git
    path: k8s
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
